export const GET_STATS = 'GET_STATS';
export const GET_STATS_FAILED = 'GET_STATS_FAILED';

export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLES_FAILED = 'GET_ARTICLES_FAILED';

export const GET_HISTORICAL_DATA = 'GET_HISTORICAL_DATA';
export const GET_HISTORICAL_DATA_FAILED = 'GET_HISTORICAL_DATA_FAILED';

export const GET_TWEETS = 'GET_TWEETS'; 
export const GET_TWEETS_FAILED = 'GET_TWEETS_FAILED'; 