export const GET_STATS = 'GET_STATS';
export const GET_STATS_FAILED = 'GET_STATS_FAILED';
export const GET_STATS_SUCCESS = 'GET_STATS_SUCCESS';

export const SET_TREND_STATUS = 'SET_TREND_STATUS';
export const SET_TREND_STATUS_SUCCESS = 'SET_TREND_STATUS_SUCCESS';
export const SET_TREND_STATUS_FAILED = 'SET_TREND_STATUS_FAILED';
export const GET_PREVIOUS_DAY_STATS = 'GET_PREVIOUS_DAY_STATS';
export const GET_PREVIOUS_DAY_STATS_SUCCESS = 'GET_PREVIOUS_DAY_STATS_SUCCESS';

export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLES_FAILED = 'GET_ARTICLES_FAILED';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';

export const GET_HISTORICAL_DATA = 'GET_HISTORICAL_DATA';
export const GET_HISTORICAL_DATA_FAILED = 'GET_HISTORICAL_DATA_FAILED';
export const GET_HISTORICAL_DATA_SUCCESS = 'GET_HISTORICAL_DATA_SUCCESS';

export const GET_TWEETS = 'GET_TWEETS'; 
export const GET_TWEETS_FAILED = 'GET_TWEETS_FAILED'; 
export const GET_TWEETS_SUCCESS = 'GET_TWEETS_SUCCESS'; 

export const SET_WORLD = 'SET_WORLD';
export const SET_COUNTRY_MODE = 'SET_COUNTRY_MODE';
export const SET_COUNTRY_DATA = 'SET_COUNTRY_DATA';
export const GET_COUNTRY_HISTORICAL_DATA = 'GET_COUNTRY_HISTORICAL_DATA';
export const GET_COUNTRY_HISTORICAL_DATA_SUCCESS = 'GET_COUNTRY_HISTORICAL_DATA_SUCCESS';
export const GET_COUNTRY_HISTORICAL_DATA_FAILED = 'GET_COUNTRY_HISTORICAL_DATA_FAILED';